[package]
name = "docker-generate"
version = "0.1.0"
authors = ["Sam <sam.mackenzie@live.com>"]
edition = "2018"
readme="README.md"
license="MIT"
description="docker file read/write"


[dependencies]
